# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/docs"
    schedule:
      interval: "monthly"
    ignore:
      - depedency-name: "PhysicalConstants" # Ignore package itself
    labels:
      - "dependencies 🖇️"
    groups:
      per-dependency:
        group-by: dependency-name
